/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "ADC_1.h"
#include "ADC_1_FILTER.h"
#include "GND_ref.h"
#include "GND_ref_aliases.h"
#include "VRef.h"
#include "VRef_aliases.h"
#include "PGA_1.h"
#include "PGA_1_PVT.h"
#include "VTest.h"
#include "VTest_aliases.h"
#include "VrGnd.h"
#include "VrGnd_aliases.h"
#include "UART_1.h"
#include "UART_1_SPI_UART.h"
#include "UART_1_PINS.h"
#include "UART_1_SPI_UART_PVT.h"
#include "UART_1_PVT.h"
#include "UART_1_BOOT.h"
#include "I2C_1.h"
#include "I2C_1_I2C.h"
#include "I2C_1_PINS.h"
#include "I2C_1_I2C_PVT.h"
#include "I2C_1_PVT.h"
#include "I2C_1_BOOT.h"
#include "BLUE_LED.h"
#include "BLUE_LED_aliases.h"
#include "RELAY_EN.h"
#include "RELAY_EN_aliases.h"
#include "Timer_1.h"
#include "Clock_1.h"
#include "Pin_1.h"
#include "Pin_1_aliases.h"
#include "Pin_2.h"
#include "Pin_2_aliases.h"
#include "AMux_1.h"
#include "isr_1.h"
#include "TCPWM_1.h"
#include "Clock_2.h"
#include "ADC_1_intSarClock.h"
#include "ADC_1_IRQ.h"
#include "ADC_1_intUabClock.h"
#include "UART_1_SCBCLK.h"
#include "I2C_1_SCBCLK.h"
#include "I2C_1_sda.h"
#include "I2C_1_sda_aliases.h"
#include "I2C_1_scl.h"
#include "I2C_1_scl_aliases.h"
#include "I2C_1_SCB_IRQ.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cm0plus_psoc4.h"
#include "CyDMA.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

