/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "ADC_1.h"
#include "ADC_1_FILTER.h"
#include "AMux_1.h"
#include "PVref_1.h"
#include "Cal_In.h"
#include "Cal_In_aliases.h"
#include "PGA_1.h"
#include "PGA_1_PVT.h"
#include "AMux_2.h"
#include "Pin_2.h"
#include "Pin_2_aliases.h"
#include "Opamp_1.h"
#include "bgRef.h"
#include "bgRef_aliases.h"
#include "Shunt_In.h"
#include "Shunt_In_aliases.h"
#include "Shunt_Gnd.h"
#include "Shunt_Gnd_aliases.h"
#include "Battery_In.h"
#include "Battery_In_aliases.h"
#include "Opamp_2.h"
#include "ADC_1_intSarClock.h"
#include "ADC_1_IRQ.h"
#include "ADC_1_intUabClock.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cm0plus_psoc4.h"
#include "CyDMA.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

